# Generated by Django 4.1.5 on 2023-08-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Branchname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100)),
                ('dep_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dic_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('date_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('not specified', 'NOT SPECIFIED')], max_length=100)),
                ('u_phone', models.CharField(max_length=10)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_address', models.TextField(max_length=1000)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('DEBIT_CARD', models.BooleanField()),
                ('CREDIT_CARD', models.BooleanField()),
                ('CHEQUE_BOOK', models.BooleanField()),
                ('ac_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.account_type')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.branchname')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roleapp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roleapp.country')),
                ('dic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.district')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.country'),
        ),
        migrations.AddField(
            model_name='branchname',
            name='dic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.district'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('not specified', 'NOT SPECIFIED')], max_length=100)),
                ('u_phone', models.CharField(max_length=10)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_address', models.TextField(max_length=1000)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('DEBIT_CARD', models.BooleanField()),
                ('CREDIT_CARD', models.BooleanField()),
                ('CHEQUE_BOOK', models.BooleanField()),
                ('ac_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.account_type')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.branchname')),
                ('dic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roleapp.district')),
            ],
        ),
    ]
