# Generated by Django 4.1.5 on 2023-08-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ac_type',
        ),
        migrations.RemoveField(
            model_name='person',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dic_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Gender',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
